---
abstract: 'Wrapper Class for the various JSON classes.'
author:
  - 'Chris Thompson <cthom@cpan.org>'
  - 'Chris Prather <chris@prather.org>'
  - 'Robin Berjon <robin@berjon.com>'
  - 'Marc Mims <marc@questright.com>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-Any
requires:
  perl: 5.008
version: 1.30
