---
abstract: 'Wrapper Class for the various JSON classes.'
author:
  - 'Chris Thompson <cthom@cpan.org>'
  - 'Chris Prather <chris@prather.org>'
  - 'Robin Berjon <robin@berjon.com>'
  - 'Marc Mims <marc@questright.com>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
build_requires:
  Test::Requires: 0
  Test::Without::Module: 0.17
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-Any
requires:
  perl: 5.008
resources:
  homepage: https://github.com/perigrin/json-any
  repository: https://github.com/perigrin/json-any.git
version: 1.32
x_contributors:
  - 'Chris Prather <cprather@hdpublishing.com>'
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
  - 'Justin Hunter <justin.d.hunter@gmail.com>'
  - 'Matthew Horsfall <wolfsage@gmail.com>'
  - 'Todd Rinaldo <toddr@cpan.org>'
  - 'marc.mims <marc.mims@daca5766-e62f-0410-9ddd-e5e43faa6270>'
  - 'nothingmuch@woobling.org <nothingmuch@woobling.org@daca5766-e62f-0410-9ddd-e5e43faa6270>'
  - 'perigrin <perigrin@daca5766-e62f-0410-9ddd-e5e43faa6270>'
  - 'robin.berjon@gmail.com <robin.berjon@gmail.com@daca5766-e62f-0410-9ddd-e5e43faa6270>'
