use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006007
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Chris
Thompson
cthom
Prather
chris
Robin
Berjon
robin
Marc
Mims
marc
Tomas
Doran
bobtfish
Dagfinn
Ilmari
Mannsåker
ilmari
Justin
Hunter
justin
Karen
Etheridge
ether
Matthew
Horsfall
wolfsage
Todd
Rinaldo
toddr
יובל
קוג
Yuval
Kogman
nothingmuch
lib
JSON
Any
